### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by artella-coding** [grwlf/oilprice#1]
Hi, if I execute the makefile with the latest version of Ur/Web I get the following error :  

```
make[1]: *** No rule to make target 'lib/uru3/Bootstrap/Bootstrap.ur', needed by  
'.cake3/tmp___lib_uru3_Bootstrap_lib_in_1'. Stop.
```

Do you know why this might be?

Thanks

**Comment by sergei-mironov** [comment]
Hi! Could you please check the lib/uru3 folder? If it is empty, then
probably should do 'git submodule update --recursive'.

Regards,
Sergey

2015-05-03 21:09 GMT+03:00 artella.coding notifications@github.com:

**Comment by artella-coding** [comment]
Hi yes it was empty. I followed your suggestion and tried `git submodule update --recursive` but that didn't do anything. I will try going into the lib directory and manually cloning the repositories. Thanks

**Comment by sergei-mironov** [comment]
Hmm, right. I think --init flag was also required in your case. The point
about submodules is that git tracks their revisions. Cloned library may be
too new to work with oilprice.

2015-05-03 22:27 GMT+03:00 artella.coding notifications@github.com:

**Comment by artella-coding** [comment]
Hi, so I started from fresh and did : 

```
git clone https://github.com/grwlf/oilprice
cd oilprice/
git submodule update --init --recursive
```

But now when I run `make` I get the following error : 

```
make[1]: *** No rule to make target 'lib/urweb-soup/autogen/Soup_css.urp.in', needed by 'lib/urweb-
soup/lib.urp'. Stop.
make[1]: Leaving directory
Makefile:370: recipe for target '.fix-multy1' failed 
make: *** [.fix-multy1] Error 2
```

**Comment by sergei-mironov** [comment]
Ha, and _that_ is a real bug :) Looks like you are the first one who tries
oilprice. I've fixed it just now, please try once again. .urp.in was under
.gitignore by mistake. Thanks.

Oh, and you don't need --recursive for building oilprice. Sorry. Try just
`git submodule update --init'  next time. This should save your disk space.

Regards,
Sergey

2015-05-03 23:01 GMT+03:00 artella.coding notifications@github.com:

**Comment by artella-coding** [comment]
Ah this time the `make` had no errors. Thanks.
